baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
relativeURLs = true

[deployment]

[[deployment.targets]]
name = "s3deploy"
URL = "s3://cugghiunieddo?region=us-east-1"

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"
    disable = false
  [[module.imports]]
    path = "github.com/yihui/hugo-xmin"
    disable = true
